Music/urls.py
from django.conf.urls import url
from . import views

app_name = 'Music'

urlpatterns = [
    # Music
    url(r'^$', views.HomView.as_view(), name='hom'),
    # url(r'^place1/', views.place1),
    # /Music/album_id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /Music/album_id/favorite
    # url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

django_tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from . import views
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.hello_world, name="Home"),
    url(r'^Music', include('Music.urls')),

]

# urlpatterns += staticfiles_urlpatterns()

Music/models.py
from django.db import models


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=350)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + '-' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=430, default='annointing')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

django_tutorial/models.py
from django.db import models


class Destination(models.Model):
    place = models.CharField(max_length=128)
    place_logo = models.CharField(max_length=472)
    continent = models.CharField(max_length=200)
    tribe = models.CharField(max_length=300)
    language = models.charField(max_length=150)


class Place(models.Model):
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=125)
    place_name = models.CharField(max_length=902)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from users.models import User


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

Music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.http import HttpResponse
from .models import Album, Song
from django.views import generic
from .models import Album


# Create your views here.
# def places(request):
#     all_albums = Album.objects.all()
#     # html = ''
#     # for album in all_albums:
#     #     url = '/Music/' + str(album.id) + '/'
#     #     html += '<a href="' + url + '">' + album.album_title + '</a><br>'
#     #     # return render(request, template_name='places/Places.html')
#     # return HttpResponse(html)
#     # template = loader.get_template('Music/hom.html')
#     # context = {'all_albums': all_albums}
#     # return HttpResponse(template.render(context,))
#     return render(request, 'Music/hom.html', {'all_albums': all_albums})
#
#
# def place1(request):
#     return render(request, template_name='places/place1.html')
#
#
# def detail(request, album_id):
#     # return HttpResponse('<h2>Details for Album id: ' + str(album_id) + '</h2>')
#     # try:
#     #     album = Album.objects.get(pk=album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404('Album does not exist')
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'Music/detail.html', {'album': album})


# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except (KeyError, Song.DoesNotExist):
#         return render(request, 'Music/detail.html', {
#             'album': album,
#             'error_message': 'You did not select a valid song',
#         })
#     else:
#         selected_song.is_favorite = True
#         selected_song.save()
#         return render(request, 'Music/detail.html', {'album': album})

class HomView(generic.ListView):
    template_name = 'Music/hom.html'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'Music/detail.html'

django_tutorial/views.py
from django.http import HttpResponse
from django.shortcuts import render


def hello_world(request):
    return HttpResponse("<h1>Hello world, this is my homepage</h1>")
    # return render(request, template_name='home/home.html')

users/views.py
from django.shortcuts import render

# Create your views here.

Music/templates/Music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Kaseruzi{% endblock %}</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="http://maxdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
<nav class='navbar navbar-inverse'>
    <div class="container-fluid">

        <div class='navbar-header'>
            <button type="button" class ="navbar-toggle" data-toggle="collapse" data-target="topNavBar">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Music:hom' %}"> Anne Kaseruzi </a>
        </div>


        <div class="collapse navbar-collapse" id="topNavBar">
              <ul class="nav navbar-nav">
                  <li class="active">
                      <a href="{% url 'Music:hom' %}">
                          <span class=" glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                      </a>
                  </li>
                  <li class="">
                      <a href="#">
                          <span class=" glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                       </a>
                  </li>
              </ul>
              <form class="navbar-form navbar-left" role="search" method="get" action="#">
                  <div class="form-group">
                     <input type="text" class="form_control" name="q" value="">
                  </div>
                  <button type="submit" class="btn btn-default">Search</button>
              </form>
               <ul class="nav navbar-nav navbar-right">
                   <li class="">
                      <a href="#">
                          <span class=" glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                       </a>
                  </li>
                   <li class="">
                      <a href="#">
                          <span class=" glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log Out
                       </a>
                  </li>
               </ul>
        </div>
    </div>
 </nav>
{% block body %}
{% endblock %}
</body>
</html>

Music/templates/Music/detail.html
{#{{ album }}#}
{% extends 'Music/base.html' %}
<title>{% block title %}Album Details{% endblock %}</title>
{% load static from staticfiles %}
{% block body %}
{#<img src="{{ album.album_logo }}">#}
<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>
{#<ul>#}
{#    {% for song in album.song_set.all %}#}
{#       <li>{{ song.song_title }}-{{ song.file_type }}</li>#}
{#    {% endfor %}#}
{#</ul>#}
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'Music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
        <label for="song{{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img class="my" src="{% static 'img/11.jpeg' %}">
        {% endif %}
       </label><br>
    {% endfor %}
     <input type="submit" value="Favorite" >
</form>
{% endblock %}

Music/templates/Music/hom.html
{% extends 'Music/base.html' %}
{% block title %}Music{% endblock  %}
{% block body %}
{% load static from staticfiles %}
<h1>Doc Gisha</h1>
{% if all_albums %}
    <h2>Here are my awesome albums:</h2>
    <ul>
        {% for album in object_list%}
            <li><a href="{% url 'Music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>You do not have any albums</h3>
{% endif %}
<p>Baby, I have been thinking.I love it when you go crazy.</p>
<span>
    <img src="{% static 'img/4.jpeg' %}">
    <img src="{% static 'img/10.jpeg' %}">
    <img src="{% static 'img/13.jpeg' %}">
    <img src="{% static 'img/received_386281518484258.jpeg' %}">
    <img src="{% static 'img/1.jpeg' %}">
    <img src="{% static 'img/9.png' %}">

</span>
{% endblock %}

templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <h1>HELLO WORLD</h1>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> This is the paragraph that brings to you all the music that you ever wanted in you life.</p>

</body>
</html>

templates/places/Places.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/test.js' %}"></script>
</head>
<body>
<h1>Doc Gisha</h1>
<p>Baby, I have been thinking.I love it when you go crazy.</p>
<img src="{% static 'img/4.jpeg'  %}">
<img src="{% static 'img/5.jpeg'  %}">
<img src="{% static 'img/6.jpeg'  %}">
<img src="{% static 'img/7.jpeg'  %}">
<img src="{% static 'img/13.jpeg'  %}">

</body>
</html>

templates/places/place1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>This is place1</p>

</body>
</html>